// <auto-generated />
namespace WebApiService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddProduct2FeatureAndReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProduct2FeatureAndReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201409161314519_AddProduct2FeatureAndReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
